<?php require 'header.phtml' ?>

<form action="addFilm" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Director</label>
                <select name="director" id="director">
                    <?php foreach ($directores as $director): ?>
                        <option value="<?=$director->id?>"><?=$director->nombre?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Año</label>
                <input required name="year" type="text" class="form-control">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Genero</label>
                <input required name="genre" type="text" class="form-control">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Sinopsis</label>
        <textarea name="synopsis" class="form-control" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Enviar</button>
</form>

<?php require 'footer.phtml' ?>

