<?php 

$titulo = 'ALERTA'; 
require_once './templates/header.phtml';
?>

<?php if ($alert) : ?>
    <div class='alert alert-<?=$type?>' role='alert'>
        <?= $alert ?>
    </div> 
<?php endif ?>

<?php 
echo'Espere, usted será redirigido en breves...';
require_once 'footer.phtml' ?>

<!-- TODO: hacer lo mismo pero para cuando se elimina y se modifica.
AGREGAR (success)
MODIFICAR (warning)
ELIMINAR (danger) -->