<?php require 'header.phtml' ?>

<div>
    <h1> <?php echo $director[0]->nombre ?> </h1>
    <div>
        <p>
            <?php
                echo $director[0]->biografia;
            ?>
        </p>
    </div>
</div>
<div>
    <ul class="list-group">
    <?php foreach($films as $film): ?>
        <li class="list-group-item item-task">
            <div class="label">
                <b><?= htmlspecialchars($film->titulo) ?></b> | <?= $film->year ?> | <?= $film->genero ?> 
                <p><?= $film->sinopsis ?></p>
            </div>
            <div class="actions">
            <?php if ((isset ($_SESSION['USER_USERNAME']))&&(($_SESSION['USER_USERNAME']=='webadmin'))): ?>
                <a href="deleteFilm/<?= $film->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            <?php endif; ?>
            <?php if ((isset ($_SESSION['USER_USERNAME']))): ?>
                <a href="modifyFilm/<?= $film->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Editar</a>
            <?php endif; ?>
                <a href="showFilm/<?= $film->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Ver más...</a>
            </div>
        </li>
    <?php endforeach ?>
    </ul>

    <p class="mt-3"><small>Mostrando <?=$count?> peliculas</small></p>
</div>





<?php require 'footer.phtml' ?>
