<?php
$titulo = 'Registrate!';
require 'header.phtml' ?>


<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<h1>Unite a nuestro club!</h1>
<form action="register" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>USUARIO</label>
                <input required name="username" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>CONTRASEÑA</label>
                <input required name="password" type="password" class="form-control">
            </div>
        </div>

    <button type="submit" class="btn btn-primary mt-2">REGISTRARSE</button>
</form>

<?php require 'footer.phtml' ?>