<?php require 'header.phtml' ?>

<ul class="list-group">
<?php foreach($directores as $director): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= htmlspecialchars($director->nombre) ?></b> | <?=$director->nacionalidad?> |  <?= $director->fecha_nacimiento ?>
            <p><?=substr($director->biografia,0,100); echo('...')?></p>
        
        </div>
        <div class="actions">
            <a href="eliminar/<?= $director->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
            <a href="showDirector/<?= $director->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Ver Más...</a>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> directores</small></p>

<?php require 'footer.phtml' ?>



