<?php require 'header.phtml' ?>
 
<h1> <?php echo $nombreDirector[0]->nombre ?> </h1>

<ul class="list-group">
<?php foreach($films as $film): ?>
    <li class="list-group-item item-task">
        <div class="label">
            <b><?= htmlspecialchars($film->titulo) ?></b> | <?= $film->year ?> | <?= $film->genero ?> 
            <p><?= $film->sinopsis ?></p>
        </div>
        <div class="actions">
        <?php if ((isset ($_SESSION['USER_USERNAME']))&&(($_SESSION['USER_USERNAME']=='webadmin'))): ?>
            <a href="deleteFilm/<?= $film->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
        <?php endif; ?>
        <?php if ((!empty($_SESSION['USER_USERNAME']))): ?>
            <a href="modifyFilm/<?= $film->id ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Editar</a>
        <?php endif; ?>
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> peliculas</small></p>

<?php require 'footer.phtml' ?>



