<?php 
$titulo = 'Modificar pelicula';
require 'header.phtml';
?>

<form action="modifyFilm/<?=$film[0]->id?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título</label>
                <input required name="title" type="text" class="form-control" value="<?=$film[0]->titulo?>">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Director</label>
                <select name="director" id="director">
                    <?php foreach ($directores as $director): ?>
                        <?php if ($director->id == $film[0]->id_director) : ?>
                            <option value="<?=$director->id?>" selected><?=$director->nombre?></option>
                        <?php else : ?>
                            <option value="<?=$director->id?>"><?=$director->nombre?></option>
                        <?php endif ?>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Año</label>
                <input required name="year" type="text" class="form-control" value="<?=$film[0]->year?>">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Genero</label>
                <input required name="genre" type="text" class="form-control" value="<?=$film[0]->genero?>">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Sinopsis</label>
        <textarea name="synopsis" class="form-control" rows="3"><?=$film[0]->sinopsis?></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Enviar</button>
</form>

<?php require 'footer.phtml' ?>
