<?php 
$titulo = "Editar un director";
require 'header.phtml' ?>

<form action="modifyDirector/<?=$director[0]->id?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Nombre</label>
                <input required name="name" type="text" class="form-control" value="<?=$director[0]->nombre?>">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Nacionalidad</label>
                <input required name="nationality" type="text" class="form-control" value="<?=$director[0]->nacionalidad?>">
            </div>
        </div>
        <div class="col-9">
            <div class="form-group">
                <label>Fecha de nacimiento</label>
                <input required name="bdate" type="date" class="form-control" max="2006-1-1" value="<?=$director[0]->fecha_nacimiento?>">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Biografía</label>
        <textarea name="bio" class="form-control" rows="3"><?=$director[0]->biografia?></textarea>
    </div>
    <button type="submit" class="btn btn-primary mt-2">Enviar</button>
</form>

<?php require 'footer.phtml' ?>